[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cgeniepy"
version = "0.8.0"
description = "A Python package to read, analyse and visualise cGENIE Earth System Model output"
license = {text = "MIT"}
